### ISSUE TITLE
Run configuration Error : PhoneGap Platform is missing

### ISSUE THREAD

**Issue by johna1203** [masahirosuzuka/phonegap-intelliJ-plugin#1]
Android Studio 0.5.5 
使っているのですが、Run / Debug Configuration の部分でエラーが
表示されているのですが？

原因わかりますでしょうか？

どうぞ、よろしくお願いします。

スクリーンショットです。

![2014-04-22 19 05 10](https://cloud.githubusercontent.com/assets/2994674/2771393/361536c8-ca6a-11e3-9635-84e508746a0a.png)

**Comment by masahirosuzuka** [comment]
コードを見直したところ
PhoneGapRunConfiguration.java
にバグが見つかりました．

修正版のv0.4.1をアップロードしたのでIntelliJのCheck for Updates...からアップデートしてください．

ありがとうございました．

**Comment by johna1203** [comment]
はい、確認してみます。
対応ありがとうございました。

また、何かあれば報告するようにします。

※とりあえず、このチケットクローズにしておきます。
