### ISSUE TITLE
Does‘t automatically load the plug-in

### ISSUE THREAD

**Issue by taolive** [masahirosuzuka/phonegap-intelliJ-plugin#10]
![jdfw](https://cloud.githubusercontent.com/assets/1654524/4330741/072dd05c-3fb5-11e4-810b-2ecff35c19b1.gif)
Please see my animated images

**Comment by anstarovoyt** [comment]
Could you submit issue to the WebStorm tracker? https://youtrack.jetbrains.com/issues/WEB

**Comment by anstarovoyt** [comment]
fixed. Should be available in the next WebStorm 9 EAP
