### ISSUE TITLE
PhoneGap/Codova plugin manager is not working

### ISSUE THREAD

**Issue by kl3ryk** [masahirosuzuka/phonegap-intelliJ-plugin#11]
ref: https://youtrack.jetbrains.com/issue/WI-24967

What steps will reproduce the problem?
1. CTRL + ALT + S
2. Go to Javascript/Phonagap configuration
3. Click add button to add plugin

What is the expected result?
Open dialog to add plugin

What happens instead?
Nothing 

There is no any error - just nothing is happening.
Platform: Windows7
PhpStrom Version: PS-138.2071

**Comment by anstarovoyt** [comment]
Hi,
see https://github.com/masahirosuzuka/phonegap-intelliJ-plugin/issues/10
it is the same issue. I will try to update plugin in the repo this week.

**Comment by anstarovoyt** [comment]
Workaround: change 'executable path'.

**Comment by anstarovoyt** [comment]
plugin updated.
