### ISSUE TITLE
Run configurations are missing after restarting webstorm

### ISSUE THREAD

**Issue by georg-bytesource** [masahirosuzuka/phonegap-intelliJ-plugin#12]
Hi there.

Whenever i restart my Webstorm, the run configurations are missing and I have to recreate them..

Could you please have a look?

Thank you.

**Comment by anstarovoyt** [comment]
I will check the problem.

**Comment by anstarovoyt** [comment]
Do you use WS8?

**Comment by georg-bytesource** [comment]
Yes, Using WS8.0.5

**Comment by anstarovoyt** [comment]
Could you please check the plugin version? The last plugin version for WS8 is 0.9

**Comment by anstarovoyt** [comment]
also you can try WS9 beta. I am sure the problem is fixed in this version.

**Comment by georg-bytesource** [comment]
Plugin version is 0.9.

Will check out WS9

**Comment by anstarovoyt** [comment]
any results?

**Comment by georg-bytesource** [comment]
Yes, we found the problem. The Workplace.xml of our project had a misformat and got rewritten every time.
