### ISSUE TITLE
Please correct the path

### ISSUE THREAD

**Issue by thesabbir** [masahirosuzuka/phonegap-intelliJ-plugin#13]
My phonegap is located at '/home/thesabbir/local/bin/phonegap' and It doesn't reckoning and showing please correct the path.
"PhoneGap dir must be '/usr/local/bin/phonegap'" - Please make this optional.

**Comment by anstarovoyt** [comment]
New version of the plugin contains field for phonegap executable. See https://confluence.jetbrains.com/display/IntelliJIDEA/PhoneGap,+Cordova+and+Ionic

**Comment by thesabbir** [comment]
@anstarovoyt thanks!
