### ISSUE TITLE
ANDROID_HOME is not set and "android" command not in your PATH

### ISSUE THREAD

**Issue by jim-y** [masahirosuzuka/phonegap-intelliJ-plugin#14]
Hi,

I get this error when trying to run my phonegap/cordova project.

```
ERROR: Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
```

Although, my PATH, and my ANDROID_HOME is correctly set.

``` bash
# Adding npm globals to PATH
export PATH=/home/jim-y/npm-global/bin:$PATH

# Adding Android SDK tools
export PATH=/home/jim-y/Tools/Android/AndroidSDK/android-sdk-linux:$PATH
export PATH=/home/jim-y/Tools/Android/AndroidSDK/android-sdk-linux/tools:$PATH
export PATH=/home/jim-y/Tools/Android/AndroidSDK/android-sdk-linux/platform-tools:$PATH

export ANDROID_HOME=/home/jim-y/Tools/Android/AndroidSDK/android-sdk-linux
export ANT_HOME=/usr/bin/ant
```

**Comment by anstarovoyt** [comment]
try to move these settings to ~/.profile and restart computer

**Comment by anstarovoyt** [comment]
any comments?

**Comment by clutwo** [comment]
worked for me. thank you!

**Comment by mbasoama** [comment]
Hi,
I have the same error. Im trying to install cordova on Ubuntu 14.0.4.
When trying to build cordova I got this error:
![screenshot from 2015-03-13 06 20 02](https://cloud.githubusercontent.com/assets/11453834/6633968/09273d9e-c949-11e4-85ee-059f404c256f.png)

when I type : echo $ANDROID_HOME I have /usr/local/android-sdk-linux
I moved the Path variables to ~/.profile

Can somone help me?

**Comment by anstarovoyt** [comment]
@mbasoama please, try to specify in '~/.profile' $PATH variable not $ANDROID_HOME

**Comment by naushadqamar** [comment]
@anstarovoyt How can I move  to ~/.profile

**Comment by extrdevs** [comment]
I has same issue similar to @mbasoama . But even after setting android home to path variable I get same error. Is it like it wont recognize until I install sdk in home?
