### ISSUE TITLE
Plugin not working for Android development in OSX Yosemite

### ISSUE THREAD

**Issue by DiegoBM** [masahirosuzuka/phonegap-intelliJ-plugin#15]
Since Apple has removed the ability to set environment variables in OSX Yosemite, it's impossible to set up the ANDROID_HOME/PATH for the android SDK, hence the plugin is unusable. Could it be possible to set a couple more input fields in the configuration screen to define those environment values for the android setting please?

**Comment by anstarovoyt** [comment]
I believe that you can anyway set PATH over ~/.profile file (require system restart). Added a new issue https://youtrack.jetbrains.com/issue/WEB-14814

**Comment by DiegoBM** [comment]
I wish I could. I went through the entire google trying to find a working fix for creating EV in Yosemite...

**Comment by anstarovoyt** [comment]
so the suggested way doesn't work?

**Comment by DiegoBM** [comment]
No, I tried and Webstorm won't get the environment variable (hence Android SDK is never found and it won't detect devices and simulators). I also tried some plist approaches that people were recommending but nothing works with Yosemite. Probably easier to configure it from the plugin

**Comment by anstarovoyt** [comment]
I have the file ~/.profile with the content 
export PATH=${PATH}:~/android-sdk/platform-tools:~/android-sdk/tools

and the functionality works correctly for android  (OS Yosemite )

**Comment by DiegoBM** [comment]
Not sure what would be happening but for sure it doesn't work for me. I have that exact same line in that exact same file, and opening WebStorm from the Dock bar it won't load the environment variables and hence it will display the SDK not found message
