### ISSUE TITLE
Unable to run ionic serve

### ISSUE THREAD

**Issue by bodiam** [masahirosuzuka/phonegap-intelliJ-plugin#16]
I'm trying to use the plugin for a command I normally use, 'ionic serve'. However, I see now way to run this with the plugin. Also, it seems like the platform is a mandatory item, which I never use when running ionic serve. Am I maybe missing something here?

Thanks!

**Comment by anstarovoyt** [comment]
Hi. Now command 'serve' is available only for the phonegap platform. I will fix the problem soon! I have one question: what IDE version do you use?

**Comment by anstarovoyt** [comment]
> Now command 'serve' is available only for the phonegap platform

I have checked the settings and in fact the ionic run configuration have the 'serve' command
If you don't have the option please, update your IDE and the plugin to the latest version.
![screen shot 2015-05-13 at 12 28 49](https://cloud.githubusercontent.com/assets/1753282/7607648/c1857ffc-f96b-11e4-8455-38da7560eb45.png)

**Comment by bodiam** [comment]
Hi @anstarovoyt, you're right, the serve option is there. What I did now, was replace the cordova executable with ionic, and that works. However, I still have to choose a platform (ios, or android), but it seems to be ignored, so I actually think everything is working, I just had the wrong cordova executable. Sorry for bothering you with this!
