### ISSUE TITLE
Looks in Unix path on Windows System?

### ISSUE THREAD

**Issue by hauntscare** [masahirosuzuka/phonegap-intelliJ-plugin#3]
Error running Android: Cannot run program "\usr\local\bin\phonegap" (in directory "C:\projects\MyApp"): CreateProcess error=2,

Hey, i am running a windows System for my cordova development.

The above Error is shown if i try to build it with you Run Configuration for Android.

I simply want it to execute "Cordova run android", is this possible?

**Comment by masahirosuzuka** [comment]
Windows supported on v0.8.2
