### ISSUE TITLE
Ability to specify the target

### ISSUE THREAD

**Issue by Foxandxss** [masahirosuzuka/phonegap-intelliJ-plugin#7]
Would be lovely (if not already possible) to be able to select device. I have always my mobile connected to the computer but I would like to use genymotion to test my apps. By default it goes to my mobile. Would be lovely to be able to specify the `--target` or even better, a popup window with the list of devices.

Cheers!

**Comment by anstarovoyt** [comment]
Hi,
It really difficult to get list of possible targets. For example ios-sim can do it if you have Xcode6+ only. So I will implement checkbox 'specify target' with text field.
Note: Now the plugin 'phonegap-intelliJ-plugin' is developing as part of Iltellij platform (and bundled to webstorm 9), therefore changes will available for new versions of Intellij IDE's (include CE) . Please, submit all feature requests and bug reports to our tracker http://youtrack.jetbrains.com/issues/WEB

**Comment by anstarovoyt** [comment]
implemented
