### ISSUE TITLE
Add possibility to set extra tool's pathes

### ISSUE THREAD

**Issue by AlexAkhremenko** [masahirosuzuka/phonegap-intelliJ-plugin#8]
Pathes of nodejs, android sdk are writen in code. This pathes are for Mac only. I need to set pathes mannualy in settings of plugin

**Comment by anstarovoyt** [comment]
Hi, what kinds of functionality you want to use with these paths? Phonegap/Cordova doesn't have a direct depend on NodeJS. For running android app Phonegap/Cordova uses global $PATH variable. In the last version of the plugin the notifications about NodeJS/SDKs are disabled.
Note: Now the plugin 'phonegap-intelliJ-plugin' is developing as part of Iltellij platform (and bundled to webstorm 9), therefore changes will available for new versions of Intellij IDE's (include CE) . Please, submit all feature requests and bug reports to our tracker http://youtrack.jetbrains.com/issues/WEB 
If you want to do contribution please use the repo: https://github.com/JetBrains/intellij-plugins/tree/master/phoneGap

**Comment by AlexAkhremenko** [comment]
Ok, I'm just using Webstorm 8 and downloaded plugin from repos. I will wait webstorm 9.

**Comment by anstarovoyt** [comment]
You also can try our WebStorm 9 EAP (http://blog.jetbrains.com/webstorm/2014/08/webstorm-9-eap/) :)
