### ISSUE TITLE
Not working in WebStorm

### ISSUE THREAD

**Issue by darkoverlordofdata** [masahirosuzuka/phonegap-intelliJ-plugin#9]
1. On the config screen, I can't enter paths because the fields are not enabled. 
2. There is no option on the import menu for PhoneGap/Cordova.

**Comment by darkoverlordofdata** [comment]
Hi, I've tried this in IntelliJ community edition and have similar issues. I am able to import a cordova project, but not much else.
1. Again, on the config screen, I can't enter paths because the fields are not enabled.
2. Build gives error:
   PhoneGap Plugin: NodeJS not detected
      a. I have no problems working with node based projects in WebStorm.
      b. On the config screen, NodeJS install directory is blank and disabled.
   PhoneGap Plugin: PhoneGap can't run
      The config screen does have the correct path to both cordova and phonegap executables.
3. Even if I manually build, I can't run. 
      a. On the run dialog, the logging options are disabled.
      b. On the run dialog, the run button is disabled. 

Everything is installed - I can build & debug cordova projects both manually and in NetBeans.

**Comment by anstarovoyt** [comment]
Hi, 
here should be answer: https://github.com/masahirosuzuka/phonegap-intelliJ-plugin/issues/8

**Comment by darkoverlordofdata** [comment]
As I said, I'm getting the same issue in IntelliJ. Regardless of whether it
actually uses the paths or not, it  just doesn't work.

On Fri, Sep 5, 2014 at 1:15 AM, Andrew Starovoyt notifications@github.com
wrote:

> Hi,
> here should be answer: #8
> https://github.com/masahirosuzuka/phonegap-intelliJ-plugin/issues/8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/masahirosuzuka/phonegap-intelliJ-plugin/issues/9#issuecomment-54596906
> .

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by anstarovoyt** [comment]
What version of intellij IDEA do you try? I wrote before that a new version of plugin (it is 138.1495) is available only for IDEA 14 EAP (because we have to do changes in the platform for some issues).

**Comment by anstarovoyt** [comment]
oh I skip this part: "There is no option on the import menu for PhoneGap/Cordova."
You don't need import project for WebStorm just use "Open ..."  quick start.

**Comment by darkoverlordofdata** [comment]
'You don't need import project for WebStorm just use "Open ..." quick
start.'

Yes, it load the project folder. But the plugins functionality is still not
working.
As far as EAP - If I wanted to use EAP, I'd already be using it

And it makes me ask - why is this plugin then available in the channel? Up
until this point, Idea only exposes plugins to a product when they .
actually work. For example, the new version of the Haxe plugin wasn't
exposed in WebStorm until it was working worked there.

I depend on WebStorm to expose functionality that is working and not waste
my time (and support time) with breakware. That is why I pay good money for
it - so that I can depend on it's rock solid functionality and focus on
writing code, not making your plugin work. Making a plugin available when
it doesn't work erodes my trust in WebStorm.

Go ahead and close this. I'll unintstall the plugin and continue using
NetBeans for cordova.

Thanks,
Bruce

On Fri, Sep 5, 2014 at 9:20 AM, Andrew Starovoyt notifications@github.com
wrote:

> What version of intellij IDEA do you try? I wrote before that a new
> version of plugin (it is 138.1495) is available only for IDEA 14 EAP
> (because we have to do changes in the platform for some issues).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/masahirosuzuka/phonegap-intelliJ-plugin/issues/9#issuecomment-54647461
> .

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by anstarovoyt** [comment]
> And it makes me ask - why is this plugin then available in the channel? 

JetBrains just helps the original author to develop the plugin (and we start to make it for WebStorm 9).

I will try to backport a part of changes to the old branch.

**Comment by anstarovoyt** [comment]
Uploaded a new version 0.9 with compatibility for IDEA13, WS8. Should be available after approving http://plugins.jetbrains.com/plugin/7436

**Comment by anstarovoyt** [comment]
Could you test the version and share feedback?

**Comment by falconmick** [comment]
I'm having issues with getting anything working with the plugin...
I had a project I wanted to import.
I followed http://confluence.jetbrains.com/display/IntelliJIDEA/PhoneGap%2C+Cordova+and+Ionic to the tee (pretty sure) first I attempted to import the cordova project from the root directory.. This failed.. So I found out I had to open it and it would figure out what to do..  but yeah... nothin worked, i did the creat run thingamabob and hit play.. nothing.. so i keep'd searching then found out about ctr+alt+shft+s opened a screen to create an android thing.. it got me to enter my jdk loc and android sdk loc, I then selected the android 19 as the choise... and still nothing..

Maybe is updated doc needed on instalation??

:( this is gettin me in a downer, its 12:30 on a work night... 

edit:
fresh install fyi

**Comment by anstarovoyt** [comment]
The last version (it is not stable yet because WS9 is not released) has a bug that tool window 'Messages' is not shown when WS(IDEA) cannot run before task. So please check 'Message' tool window for errors.

If there is no errors:
Could you create a sample project and try to run it?
From here: http://confluence.jetbrains.com/display/IntelliJIDEA/PhoneGap%2C+Cordova+and+Ionic

> Creating a new application takes just a tad longer: click File → New Project…, then select Static Web, and then PhoneGap/Cordova App.
> If you use WebStorm do 'Create New Project → PhoneGap/Cordova'.

It is just for check that your settings are correct.

**Comment by falconmick** [comment]
This is my first time in the IDE so I wouldn't put it past me to misconfigure..

Will check after work
